#!/bin/sh /etc/rc.common

# 采用 OpenWrt 现代 procd 守护进程规范
USE_PROCD=1
START=99

PROG=/usr/bin/kcptun-client

start_service() {
	# 此处为启动命令示例，可根据实际需求修改读取 uci 配置
	# 默认为读取 /etc/kcptun.json 或传入特定参数
	
	procd_open_instance
	procd_set_param command $PROG 
	# 示范：如果使用配置文件可以取消下面这行的注释
	# procd_append_param command -c /etc/kcptun.json
	
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
